INSERT INTO USER_GROUP(ID, NAME) SELECT 1, 'admins' WHERE NOT EXISTS (SELECT * FROM USER_GROUP WHERE ID = 1);
INSERT INTO USER(ID, NAME, PASSWORD_HASH) SELECT 1, 'admin', '$2a$04$3PdcVf13FB2H0WZzkvK3celBZlP148EEble1sjYXocqhyuaI.hDJu' WHERE NOT EXISTS (SELECT * FROM USER WHERE ID = 1);
INSERT INTO USER_MEMBERSHIP(GROUP_ID, USER_ID) SELECT 1, 1 WHERE NOT EXISTS (SELECT * FROM USER_MEMBERSHIP WHERE GROUP_ID = 1 AND USER_ID= 1);
